spring.application.name=Find Stock Manager
#server.port=9000
#para que esten conectados los documentos:
spring.messages.basename=mensajes
# consola en navegador web
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:fsmdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
#cargar los archivos iniciales
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
# para que encuentre los sql de inicializacion de datos en otra ubicación
spring.sql.init.data-locations=classpath:data.sql
# Habilita la sobrescritura de beans
spring.main.allow-bean-definition-overriding=true
# Configuración de Logging
# Muestra los logs de INFO de tu paquete de controladores (ajusta el paquete si es diferente)
logging.level.es.examplepb.findstockmanager.controladores=INFO
# Configuración de JPA/Hibernate para mostrar SQL
# Muestra las consultas SQL generadas en la consola
spring.jpa.show-sql=true
# Formatea las consultas SQL para que sean más legibles
spring.jpa.properties.hibernate.format_sql=true
# Configuración explícita de Open Session in View para silenciar la advertencia
spring.jpa.open-in-view=true